config/routes.rb
Rails.application.routes.draw do
  root :to => 'memos#index'
  resources :memos, only: [:index, :update, :destroy, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
    validates :title, presence: true, length: { minimum: 2, maximum: 32 }
    validates :description, presence: true, length: { minimum: 2, maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memo_new = Memo.new
    @memos = Memo.all
  end
 
  def create
    @memo_new = Memo.new(memos_params)
    @memos = Memo.all
    if @memo_new.save
      redirect_to root_path
    else
      render action: "index"
    end
  end
 
  def update
    @memo = Memo.find(params[:id])
    @memo.update(memos_params)
    redirect_to root_path
  end
 
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to root_path
  end
 
  private
 
  def memos_params
    params.require(:memo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper header-color">
      <div class="container">
        <h1>MemoApp</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/memos/index.html.erb
<div class="wrapper">
    <div class="container flex-start">
        <div class="col-box-1">
            <h2>メモ一覧</h2>
        </div>

        <% if @memo_new.errors.any? %>
            <div class="col-box-1">
                <h3><%= @memo_new.errors.count %>件のエラーが発生しました。</h3>
                <ul>
                    <% @memo_new.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="col-box-3">
            <%= form_with model: @memo_new, url: memos_path, local: true, method: :post do |f| %>
                <div class="memo-header">
                    <%= f.text_field :title, placeholder: "タイトル", class: "form-box" %>
                </div>
                <div class="memo-center">
                    <%= f.text_area :description, placeholder: "メモ", class: "form-box" %>
                </div>
                <div class="memo-footer">
                    <%= f.submit "作成", class: "btn" %>
                </div>
            <% end %>
        </div>

        <% @memos.reverse.each do |memo| %>
            <div class="col-box-3">
                <%= form_with model: memo, url: memo_path(memo.id), local: true, method: :patch do |f| %>
                    <div class="memo-header">
                        <%= f.text_field :title, placeholder: "タイトル", class: "form-box" %>
                    </div>
                    <div class="memo-center">
                        <%= f.text_area :description, placeholder: "メモ", class: "form-box" %>
                    </div>
                    <div class="memo-footer">
                        <%= f.submit "更新", class: "btn" %>
                    </div>
                <% end %>
                <div class="memo-other">
                    <%= button_to "削除", memo_path(memo.id), method: :delete, class: "btn" %>
                </div>
            </div>
        <% end %>
    </div>
</div>